Repository OpenVoiceOS/skill-ovos-setup, pull requests merged in 2022-10, with the labels that each got.

#23 selene_api -> ovos_backend_client
  __init__.py
  requirements.txt
Labels: question, refactor

#24 fix/pairing event emit
  __init__.py
Labels: bug

#25 fix/serialization of enum
  __init__.py
Labels: bug

#27 Fix config setting to match signatures in `SetupManager`
  __init__.py
Labels: bug

#30 Setup
  setup.py
  version.py
Labels: packaging

#35 fix Setup
  setup.py
Labels: bug

#34 Fix/pairing
  __init__.py
Labels: bug

#36 deprecate_disabled_flag + cleanup code
  __init__.py
Labels: bug

#37 feat/setup_stage_flags
  __init__.py
Labels: enhancement

#39 Fix typo in setup.py getting skill/package name
  setup.py
Labels: bug, packaging

#38 fix/stt_tts_selection
  __init__.py
  ui/STTListMenu.qml
  ui/TTSListMenu.qml
Labels: bug

#41 fix how to see if we need gui or voice and condition back button on backend selection page
  __init__.py
  ui/BackendSelect.qml
Labels: bug

#42 bump requirements.txt
  .github/workflows/build_tests.yml
  requirements.txt
Labels: packaging

#43 Add german locale
  locale/de-de/dialog/already_paired.dialog
  locale/de-de/dialog/ask.selection.intro.dialog
  locale/de-de/dialog/backend_confirm.dialog
  locale/de-de/dialog/backend_confirm_gui.dialog
  locale/de-de/dialog/backend_intro.dialog
  locale/de-de/dialog/backend_mycroft.dialog
  locale/de-de/dialog/backend_not_understood.dialog
  locale/de-de/dialog/backend_options_intro.dialog
  locale/de-de/dialog/backend_prompt.dialog
  locale/de-de/dialog/choice_failed.dialog
  locale/de-de/dialog/codes.value
  locale/de-de/dialog/confirm_stt.dialog
  locale/de-de/dialog/confirm_tts.dialog
  locale/de-de/dialog/intro_confirm_local.dialog
  locale/de-de/dialog/intro_confirm_no_backend.dialog
  locale/de-de/dialog/intro_confirm_selene.dialog
  locale/de-de/dialog/language_menu.dialog
  locale/de-de/dialog/local_backend_url_prompt.dialog
  locale/de-de/dialog/pairing.code.dialog
  locale/de-de/dialog/pairing.intro.dialog
  locale/de-de/dialog/pairing.not.paired.dialog
  locale/de-de/dialog/pairing.paired.dialog
  locale/de-de/dialog/select_option_gui.dialog
  locale/de-de/dialog/select_stt.dialog
  locale/de-de/dialog/select_tts.dialog
  locale/de-de/dialog/stt_intro.dialog
  locale/de-de/dialog/tts_intro.dialog
  locale/de-de/dialog/unexpected.error.restarting.dialog
  locale/de-de/dialog/welcome_screen.dialog
  locale/de-de/vocab/device.voc
  locale/de-de/vocab/local_backend.voc
  locale/de-de/vocab/no_backend.voc
  locale/de-de/vocab/pairing.voc
  locale/de-de/vocab/selene_backend.voc
Labels: enhancement

#44 feat/autopair_personal_backend
  __init__.py
  requirements.txt
Labels: enhancement

#46 fix/enum_string
  __init__.py
Labels: bug

#47 feat/sorted_plugins
  requirements.txt
Labels: enhancement, packaging

#7 feat/workflows
  .github/workflows/auto_translate.yml
  .github/workflows/build_tests.yml
  .github/workflows/license_tests.yml
  .github/workflows/prepare_skillstore.yml
  .github/workflows/unit_tests.yml
  .gitignore
  scripts/prepare_skillstore.py
  scripts/translate.py
  test/license_tests.py
  test/unittests/osm_tests.py
  test/unittests/plugin_tests.py
  test/unittests/test_skill_loading.py
Labels: automations

#51 disable converse completely if using gui mode as its totally broken
  __init__.py
Labels: bug

#55 fix GUI crashing with too many options reported by plugins
  __init__.py
Labels: bug

#59 Aix rebased listview
  __init__.py
  requirements.txt
  ui/ProcessLoader.qml
  ui/STTListMenu.qml
  ui/TTSListMenu.qml
  ui/icons/female.svg
  ui/icons/male.svg
Labels: enhancement
